---
all:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: default_user
    ansible_ssh_pass: 123
    # W labie używamy sshpass, w produkcji używalibyśmy kluczy SSH
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Router brzegowy
    isp:
      hosts:
        router_isp:
          ansible_host: 100.64.2.1  # Używamy adresu wewnętrznego (brama dla Hubów)
          
    # Huby DMVPN
    hubs:
      hosts:
        hub1:
          ansible_host: 100.64.2.2
        hub2:
          ansible_host: 100.64.3.2
          
    # Oddziały (Spokes)
    spokes:
      hosts:
        spoke1:
          ansible_host: 100.64.4.2
        spoke2:
          ansible_host: 100.64.5.2
        spoke3:
          ansible_host: 100.64.6.2
